import type { VinTarget } from "./types";
import { deriveVinPrefix, normalizeVinPattern } from "./vin-patterns";

function buildTarget(
  key: string,
  label: string,
  carType: string,
  marker: string,
  vinPattern: string,
  yearFrom: number,
  yearTo: number,
  copartSlug: string,
  iaaiPath: string,
  sortOrder: number,
): Omit<VinTarget, "id" | "createdAt" | "updatedAt"> {
  const normalizedVinPattern = normalizeVinPattern(vinPattern);
  return {
    key,
    label,
    carType,
    marker,
    vinPattern: normalizedVinPattern,
    vinPrefix: deriveVinPrefix(normalizedVinPattern),
    yearFrom,
    yearTo,
    copartSlug,
    iaaiPath,
    enabledCopart: true,
    enabledIaai: true,
    active: true,
    sortOrder,
  };
}

export const DEFAULT_TARGETS = [
  buildTarget(
    "model-3-ec",
    "Model 3",
    "Tesla Model 3",
    "Model 3 · 5YJ3E1EC",
    "5YJ3E1EC",
    2020,
    2023,
    "model-3",
    "Model%203",
    10,
  ),
  buildTarget(
    "model-3-et",
    "Model 3",
    "Tesla Model 3",
    "Model 3 · 5YJ3E1ET",
    "5YJ3E1ET",
    2024,
    2027,
    "model-3",
    "Model%203",
    20,
  ),
  buildTarget(
    "model-y-gdee-tf",
    "Model Y",
    "Tesla Model Y",
    "Model Y · 7SAYGDEE-TF family",
    "7SAYGDEE*TF",
    2024,
    2027,
    "model-y",
    "Model%20Y",
    30,
  ),
  buildTarget(
    "model-y-gdee-ta",
    "Model Y",
    "Tesla Model Y",
    "Model Y · 7SAYGDEE-TA family",
    "7SAYGDEE*TA",
    2024,
    2027,
    "model-y",
    "Model%20Y",
    40,
  ),
  buildTarget(
    "model-y-gaee-tf",
    "Model Y",
    "Tesla Model Y",
    "Model Y · 7SAYGAEE-TF family",
    "7SAYGAEE*TF",
    2024,
    2027,
    "model-y",
    "Model%20Y",
    50,
  ),
  buildTarget(
    "model-y-gaee-ta",
    "Model Y",
    "Tesla Model Y",
    "Model Y · 7SAYGAEE-TA family",
    "7SAYGAEE*TA",
    2024,
    2027,
    "model-y",
    "Model%20Y",
    60,
  ),
];
