import { generateKeyPairSync, randomBytes } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import path from "node:path";

interface Args {
  baseUrl: string;
  collectorUpdateBaseUrl: string;
  envFile: string;
  keysDir: string;
  force: boolean;
}

function parseArgs(argv: string[]): Args {
  const getValue = (flag: string, fallback: string) => {
    const index = argv.indexOf(flag);
    return index !== -1 && argv[index + 1] ? argv[index + 1] : fallback;
  };

  return {
    baseUrl: getValue("--base-url", "https://auc.ldev.cloud").replace(/\/$/, ""),
    collectorUpdateBaseUrl: getValue("--collector-update-base-url", "").replace(/\/$/, ""),
    envFile: path.resolve(getValue("--env-file", ".env")),
    keysDir: path.resolve(getValue("--keys-dir", "runner-keys")),
    force: argv.includes("--force"),
  };
}

function randomToken(bytes = 32): string {
  return randomBytes(bytes).toString("hex");
}

function ensureDirectory(targetPath: string): void {
  mkdirSync(targetPath, { recursive: true });
}

function writeIfMissing(filePath: string, content: string, force: boolean): void {
  if (existsSync(filePath) && !force) {
    return;
  }
  writeFileSync(filePath, content, "utf8");
}

function toRelativeEnvPath(envFile: string, targetFile: string): string {
  const relative = path.relative(path.dirname(envFile), targetFile);
  if (!relative || relative === "") {
    return ".";
  }
  return relative.startsWith(".") ? relative : `./${relative}`;
}

function createCollectorSigningKeys(keysDir: string, force: boolean): { privateKeyFile: string; publicKeyFile: string; created: boolean } {
  ensureDirectory(keysDir);
  const privateKeyFile = path.join(keysDir, "collector-signing-key.pem");
  const publicKeyFile = path.join(keysDir, "collector-signing-key.pub.pem");
  const alreadyExists = existsSync(privateKeyFile) && existsSync(publicKeyFile);

  if (alreadyExists && !force) {
    return {
      privateKeyFile,
      publicKeyFile,
      created: false,
    };
  }

  const { privateKey, publicKey } = generateKeyPairSync("ed25519");
  writeFileSync(
    privateKeyFile,
    privateKey.export({ format: "pem", type: "pkcs8" }).toString(),
    "utf8",
  );
  writeFileSync(
    publicKeyFile,
    publicKey.export({ format: "pem", type: "spki" }).toString(),
    "utf8",
  );

  return {
    privateKeyFile,
    publicKeyFile,
    created: true,
  };
}

function buildEnvFile(args: Args, privateKeyFile: string, publicKeyFile: string): string {
  const privateKeyPath = toRelativeEnvPath(args.envFile, privateKeyFile);
  const publicKeyPath = toRelativeEnvPath(args.envFile, publicKeyFile);
  const collectorUpdateBaseUrl = args.collectorUpdateBaseUrl || `${args.baseUrl}/collector/runtime`;
  return [
    "# Generated by bun scripts/generate-env.ts",
    `AUCTION_BASE_URL=${args.baseUrl}`,
    `AUCTION_COLLECTOR_UPDATE_BASE_URL=${collectorUpdateBaseUrl}`,
    "HOST=0.0.0.0",
    "PORT=3005",
    `AUCTION_ADMIN_PASSWORD=${randomToken(18)}`,
    `BETTER_AUTH_SECRET=${randomToken(32)}`,
    `AUCTION_INGEST_TOKEN=${randomToken(32)}`,
    "AUCTION_ADMIN_EMAILS=luka@lnh.ge",
    "AUCTION_TRUSTED_ORIGINS=",
    "AUCTION_USE_SECURE_COOKIES=false",
    `AUCTION_COLLECTOR_PRIVATE_KEY_FILE=${privateKeyPath}`,
    `AUCTION_COLLECTOR_PUBLIC_KEY_FILE=${publicKeyPath}`,
    "",
  ].join("\n");
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  ensureDirectory(path.dirname(args.envFile));

  if (existsSync(args.envFile) && !args.force) {
    console.error(`Refusing to overwrite existing ${args.envFile}. Re-run with --force if you want to regenerate it.`);
    process.exit(1);
  }

  const keyInfo = createCollectorSigningKeys(args.keysDir, args.force);
  const envContent = buildEnvFile(args, keyInfo.privateKeyFile, keyInfo.publicKeyFile);
  writeIfMissing(args.envFile, envContent, true);

  console.log(
    JSON.stringify(
      {
        ok: true,
        envFile: args.envFile,
        keysDir: args.keysDir,
        baseUrl: args.baseUrl,
        collectorUpdateBaseUrl: args.collectorUpdateBaseUrl || `${args.baseUrl}/collector/runtime`,
        privateKeyFile: keyInfo.privateKeyFile,
        publicKeyFile: keyInfo.publicKeyFile,
        keysCreated: keyInfo.created,
        envPreview: readFileSync(args.envFile, "utf8")
          .split("\n")
          .map((line) => (line.startsWith("#") || !line.includes("=") ? line : `${line.split("=")[0]}=***`)),
      },
      null,
      2,
    ),
  );
}

main();
