/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoldRouteImport } from './routes/sold'
import { Route as HealthRouteImport } from './routes/health'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ImagesImageIdRouteImport } from './routes/images/$imageId'
import { Route as CollectorRuntimeRouteImport } from './routes/collector/runtime'
import { Route as ApiSyncRunsRouteImport } from './routes/api/sync-runs'
import { Route as ApiScrapeConfigRouteImport } from './routes/api/scrape-config'
import { Route as ApiLotsRouteImport } from './routes/api/lots'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as AdminTargetsRouteImport } from './routes/admin/targets'
import { Route as AdminSignupRouteImport } from './routes/admin/signup'
import { Route as AdminLogoutRouteImport } from './routes/admin/logout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminHistoryRouteImport } from './routes/admin/history'
import { Route as LotsSourceKeyLotNumberRouteImport } from './routes/lots/$sourceKey/$lotNumber'
import { Route as LotsLotIdRejectRouteImport } from './routes/lots/$lotId/reject'
import { Route as CollectorRuntimeSplatRouteImport } from './routes/collector/runtime/$'
import { Route as ApiSoldPriceResultsRouteImport } from './routes/api/sold-price/results'
import { Route as ApiSoldPriceQueueRouteImport } from './routes/api/sold-price/queue'
import { Route as ApiPushVapidKeyRouteImport } from './routes/api/push/vapid-key'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as ApiIngestTargetUpdatesRouteImport } from './routes/api/ingest/target-updates'
import { Route as ApiIngestImageStateRouteImport } from './routes/api/ingest/image-state'
import { Route as ApiIngestImageRouteImport } from './routes/api/ingest/image'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminTargetsTargetIdRouteImport } from './routes/admin/targets/$targetId'
import { Route as AdminHistoryDeleteRouteImport } from './routes/admin/history/delete'
import { Route as AdminTargetsTargetIdRemoveRouteImport } from './routes/admin/targets/$targetId/remove'
import { Route as AdminLotsLotIdRestoreRouteImport } from './routes/admin/lots/$lotId/restore'
import { Route as AdminLotsLotIdRemoveRouteImport } from './routes/admin/lots/$lotId/remove'
import { Route as AdminLotsLotIdDeleteRouteImport } from './routes/admin/lots/$lotId/delete'
import { Route as AdminLotsLotIdApproveRouteImport } from './routes/admin/lots/$lotId/approve'

const SoldRoute = SoldRouteImport.update({
  id: '/sold',
  path: '/sold',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesImageIdRoute = ImagesImageIdRouteImport.update({
  id: '/images/$imageId',
  path: '/images/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorRuntimeRoute = CollectorRuntimeRouteImport.update({
  id: '/collector/runtime',
  path: '/collector/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRunsRoute = ApiSyncRunsRouteImport.update({
  id: '/api/sync-runs',
  path: '/api/sync-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeConfigRoute = ApiScrapeConfigRouteImport.update({
  id: '/api/scrape-config',
  path: '/api/scrape-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLotsRoute = ApiLotsRouteImport.update({
  id: '/api/lots',
  path: '/api/lots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTargetsRoute = AdminTargetsRouteImport.update({
  id: '/admin/targets',
  path: '/admin/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin/signup',
  path: '/admin/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogoutRoute = AdminLogoutRouteImport.update({
  id: '/admin/logout',
  path: '/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/admin/history',
  path: '/admin/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsSourceKeyLotNumberRoute = LotsSourceKeyLotNumberRouteImport.update({
  id: '/lots/$sourceKey/$lotNumber',
  path: '/lots/$sourceKey/$lotNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsLotIdRejectRoute = LotsLotIdRejectRouteImport.update({
  id: '/lots/$lotId/reject',
  path: '/lots/$lotId/reject',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorRuntimeSplatRoute = CollectorRuntimeSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CollectorRuntimeRoute,
} as any)
const ApiSoldPriceResultsRoute = ApiSoldPriceResultsRouteImport.update({
  id: '/api/sold-price/results',
  path: '/api/sold-price/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoldPriceQueueRoute = ApiSoldPriceQueueRouteImport.update({
  id: '/api/sold-price/queue',
  path: '/api/sold-price/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushVapidKeyRoute = ApiPushVapidKeyRouteImport.update({
  id: '/api/push/vapid-key',
  path: '/api/push/vapid-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestTargetUpdatesRoute = ApiIngestTargetUpdatesRouteImport.update({
  id: '/target-updates',
  path: '/target-updates',
  getParentRoute: () => ApiIngestRoute,
} as any)
const ApiIngestImageStateRoute = ApiIngestImageStateRouteImport.update({
  id: '/image-state',
  path: '/image-state',
  getParentRoute: () => ApiIngestRoute,
} as any)
const ApiIngestImageRoute = ApiIngestImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ApiIngestRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTargetsTargetIdRoute = AdminTargetsTargetIdRouteImport.update({
  id: '/$targetId',
  path: '/$targetId',
  getParentRoute: () => AdminTargetsRoute,
} as any)
const AdminHistoryDeleteRoute = AdminHistoryDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => AdminHistoryRoute,
} as any)
const AdminTargetsTargetIdRemoveRoute =
  AdminTargetsTargetIdRemoveRouteImport.update({
    id: '/remove',
    path: '/remove',
    getParentRoute: () => AdminTargetsTargetIdRoute,
  } as any)
const AdminLotsLotIdRestoreRoute = AdminLotsLotIdRestoreRouteImport.update({
  id: '/admin/lots/$lotId/restore',
  path: '/admin/lots/$lotId/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLotsLotIdRemoveRoute = AdminLotsLotIdRemoveRouteImport.update({
  id: '/admin/lots/$lotId/remove',
  path: '/admin/lots/$lotId/remove',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLotsLotIdDeleteRoute = AdminLotsLotIdDeleteRouteImport.update({
  id: '/admin/lots/$lotId/delete',
  path: '/admin/lots/$lotId/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLotsLotIdApproveRoute = AdminLotsLotIdApproveRouteImport.update({
  id: '/admin/lots/$lotId/approve',
  path: '/admin/lots/$lotId/approve',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/health': typeof HealthRoute
  '/sold': typeof SoldRoute
  '/admin/history': typeof AdminHistoryRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/targets': typeof AdminTargetsRouteWithChildren
  '/api/ingest': typeof ApiIngestRouteWithChildren
  '/api/lots': typeof ApiLotsRoute
  '/api/scrape-config': typeof ApiScrapeConfigRoute
  '/api/sync-runs': typeof ApiSyncRunsRoute
  '/collector/runtime': typeof CollectorRuntimeRouteWithChildren
  '/images/$imageId': typeof ImagesImageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/history/delete': typeof AdminHistoryDeleteRoute
  '/admin/targets/$targetId': typeof AdminTargetsTargetIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ingest/image': typeof ApiIngestImageRoute
  '/api/ingest/image-state': typeof ApiIngestImageStateRoute
  '/api/ingest/target-updates': typeof ApiIngestTargetUpdatesRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/vapid-key': typeof ApiPushVapidKeyRoute
  '/api/sold-price/queue': typeof ApiSoldPriceQueueRoute
  '/api/sold-price/results': typeof ApiSoldPriceResultsRoute
  '/collector/runtime/$': typeof CollectorRuntimeSplatRoute
  '/lots/$lotId/reject': typeof LotsLotIdRejectRoute
  '/lots/$sourceKey/$lotNumber': typeof LotsSourceKeyLotNumberRoute
  '/admin/lots/$lotId/approve': typeof AdminLotsLotIdApproveRoute
  '/admin/lots/$lotId/delete': typeof AdminLotsLotIdDeleteRoute
  '/admin/lots/$lotId/remove': typeof AdminLotsLotIdRemoveRoute
  '/admin/lots/$lotId/restore': typeof AdminLotsLotIdRestoreRoute
  '/admin/targets/$targetId/remove': typeof AdminTargetsTargetIdRemoveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/health': typeof HealthRoute
  '/sold': typeof SoldRoute
  '/admin/history': typeof AdminHistoryRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/targets': typeof AdminTargetsRouteWithChildren
  '/api/ingest': typeof ApiIngestRouteWithChildren
  '/api/lots': typeof ApiLotsRoute
  '/api/scrape-config': typeof ApiScrapeConfigRoute
  '/api/sync-runs': typeof ApiSyncRunsRoute
  '/collector/runtime': typeof CollectorRuntimeRouteWithChildren
  '/images/$imageId': typeof ImagesImageIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/history/delete': typeof AdminHistoryDeleteRoute
  '/admin/targets/$targetId': typeof AdminTargetsTargetIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ingest/image': typeof ApiIngestImageRoute
  '/api/ingest/image-state': typeof ApiIngestImageStateRoute
  '/api/ingest/target-updates': typeof ApiIngestTargetUpdatesRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/vapid-key': typeof ApiPushVapidKeyRoute
  '/api/sold-price/queue': typeof ApiSoldPriceQueueRoute
  '/api/sold-price/results': typeof ApiSoldPriceResultsRoute
  '/collector/runtime/$': typeof CollectorRuntimeSplatRoute
  '/lots/$lotId/reject': typeof LotsLotIdRejectRoute
  '/lots/$sourceKey/$lotNumber': typeof LotsSourceKeyLotNumberRoute
  '/admin/lots/$lotId/approve': typeof AdminLotsLotIdApproveRoute
  '/admin/lots/$lotId/delete': typeof AdminLotsLotIdDeleteRoute
  '/admin/lots/$lotId/remove': typeof AdminLotsLotIdRemoveRoute
  '/admin/lots/$lotId/restore': typeof AdminLotsLotIdRestoreRoute
  '/admin/targets/$targetId/remove': typeof AdminTargetsTargetIdRemoveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/health': typeof HealthRoute
  '/sold': typeof SoldRoute
  '/admin/history': typeof AdminHistoryRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/targets': typeof AdminTargetsRouteWithChildren
  '/api/ingest': typeof ApiIngestRouteWithChildren
  '/api/lots': typeof ApiLotsRoute
  '/api/scrape-config': typeof ApiScrapeConfigRoute
  '/api/sync-runs': typeof ApiSyncRunsRoute
  '/collector/runtime': typeof CollectorRuntimeRouteWithChildren
  '/images/$imageId': typeof ImagesImageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/history/delete': typeof AdminHistoryDeleteRoute
  '/admin/targets/$targetId': typeof AdminTargetsTargetIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ingest/image': typeof ApiIngestImageRoute
  '/api/ingest/image-state': typeof ApiIngestImageStateRoute
  '/api/ingest/target-updates': typeof ApiIngestTargetUpdatesRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/vapid-key': typeof ApiPushVapidKeyRoute
  '/api/sold-price/queue': typeof ApiSoldPriceQueueRoute
  '/api/sold-price/results': typeof ApiSoldPriceResultsRoute
  '/collector/runtime/$': typeof CollectorRuntimeSplatRoute
  '/lots/$lotId/reject': typeof LotsLotIdRejectRoute
  '/lots/$sourceKey/$lotNumber': typeof LotsSourceKeyLotNumberRoute
  '/admin/lots/$lotId/approve': typeof AdminLotsLotIdApproveRoute
  '/admin/lots/$lotId/delete': typeof AdminLotsLotIdDeleteRoute
  '/admin/lots/$lotId/remove': typeof AdminLotsLotIdRemoveRoute
  '/admin/lots/$lotId/restore': typeof AdminLotsLotIdRestoreRoute
  '/admin/targets/$targetId/remove': typeof AdminTargetsTargetIdRemoveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/health'
    | '/sold'
    | '/admin/history'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/signup'
    | '/admin/targets'
    | '/api/ingest'
    | '/api/lots'
    | '/api/scrape-config'
    | '/api/sync-runs'
    | '/collector/runtime'
    | '/images/$imageId'
    | '/admin/'
    | '/admin/history/delete'
    | '/admin/targets/$targetId'
    | '/api/auth/$'
    | '/api/ingest/image'
    | '/api/ingest/image-state'
    | '/api/ingest/target-updates'
    | '/api/push/subscribe'
    | '/api/push/vapid-key'
    | '/api/sold-price/queue'
    | '/api/sold-price/results'
    | '/collector/runtime/$'
    | '/lots/$lotId/reject'
    | '/lots/$sourceKey/$lotNumber'
    | '/admin/lots/$lotId/approve'
    | '/admin/lots/$lotId/delete'
    | '/admin/lots/$lotId/remove'
    | '/admin/lots/$lotId/restore'
    | '/admin/targets/$targetId/remove'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/health'
    | '/sold'
    | '/admin/history'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/signup'
    | '/admin/targets'
    | '/api/ingest'
    | '/api/lots'
    | '/api/scrape-config'
    | '/api/sync-runs'
    | '/collector/runtime'
    | '/images/$imageId'
    | '/admin'
    | '/admin/history/delete'
    | '/admin/targets/$targetId'
    | '/api/auth/$'
    | '/api/ingest/image'
    | '/api/ingest/image-state'
    | '/api/ingest/target-updates'
    | '/api/push/subscribe'
    | '/api/push/vapid-key'
    | '/api/sold-price/queue'
    | '/api/sold-price/results'
    | '/collector/runtime/$'
    | '/lots/$lotId/reject'
    | '/lots/$sourceKey/$lotNumber'
    | '/admin/lots/$lotId/approve'
    | '/admin/lots/$lotId/delete'
    | '/admin/lots/$lotId/remove'
    | '/admin/lots/$lotId/restore'
    | '/admin/targets/$targetId/remove'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/health'
    | '/sold'
    | '/admin/history'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/signup'
    | '/admin/targets'
    | '/api/ingest'
    | '/api/lots'
    | '/api/scrape-config'
    | '/api/sync-runs'
    | '/collector/runtime'
    | '/images/$imageId'
    | '/admin/'
    | '/admin/history/delete'
    | '/admin/targets/$targetId'
    | '/api/auth/$'
    | '/api/ingest/image'
    | '/api/ingest/image-state'
    | '/api/ingest/target-updates'
    | '/api/push/subscribe'
    | '/api/push/vapid-key'
    | '/api/sold-price/queue'
    | '/api/sold-price/results'
    | '/collector/runtime/$'
    | '/lots/$lotId/reject'
    | '/lots/$sourceKey/$lotNumber'
    | '/admin/lots/$lotId/approve'
    | '/admin/lots/$lotId/delete'
    | '/admin/lots/$lotId/remove'
    | '/admin/lots/$lotId/restore'
    | '/admin/targets/$targetId/remove'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  HealthRoute: typeof HealthRoute
  SoldRoute: typeof SoldRoute
  AdminHistoryRoute: typeof AdminHistoryRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogoutRoute: typeof AdminLogoutRoute
  AdminSignupRoute: typeof AdminSignupRoute
  AdminTargetsRoute: typeof AdminTargetsRouteWithChildren
  ApiIngestRoute: typeof ApiIngestRouteWithChildren
  ApiLotsRoute: typeof ApiLotsRoute
  ApiScrapeConfigRoute: typeof ApiScrapeConfigRoute
  ApiSyncRunsRoute: typeof ApiSyncRunsRoute
  CollectorRuntimeRoute: typeof CollectorRuntimeRouteWithChildren
  ImagesImageIdRoute: typeof ImagesImageIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiPushVapidKeyRoute: typeof ApiPushVapidKeyRoute
  ApiSoldPriceQueueRoute: typeof ApiSoldPriceQueueRoute
  ApiSoldPriceResultsRoute: typeof ApiSoldPriceResultsRoute
  LotsLotIdRejectRoute: typeof LotsLotIdRejectRoute
  LotsSourceKeyLotNumberRoute: typeof LotsSourceKeyLotNumberRoute
  AdminLotsLotIdApproveRoute: typeof AdminLotsLotIdApproveRoute
  AdminLotsLotIdDeleteRoute: typeof AdminLotsLotIdDeleteRoute
  AdminLotsLotIdRemoveRoute: typeof AdminLotsLotIdRemoveRoute
  AdminLotsLotIdRestoreRoute: typeof AdminLotsLotIdRestoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sold': {
      id: '/sold'
      path: '/sold'
      fullPath: '/sold'
      preLoaderRoute: typeof SoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$imageId': {
      id: '/images/$imageId'
      path: '/images/$imageId'
      fullPath: '/images/$imageId'
      preLoaderRoute: typeof ImagesImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/runtime': {
      id: '/collector/runtime'
      path: '/collector/runtime'
      fullPath: '/collector/runtime'
      preLoaderRoute: typeof CollectorRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-runs': {
      id: '/api/sync-runs'
      path: '/api/sync-runs'
      fullPath: '/api/sync-runs'
      preLoaderRoute: typeof ApiSyncRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape-config': {
      id: '/api/scrape-config'
      path: '/api/scrape-config'
      fullPath: '/api/scrape-config'
      preLoaderRoute: typeof ApiScrapeConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lots': {
      id: '/api/lots'
      path: '/api/lots'
      fullPath: '/api/lots'
      preLoaderRoute: typeof ApiLotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/targets': {
      id: '/admin/targets'
      path: '/admin/targets'
      fullPath: '/admin/targets'
      preLoaderRoute: typeof AdminTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/admin/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logout': {
      id: '/admin/logout'
      path: '/admin/logout'
      fullPath: '/admin/logout'
      preLoaderRoute: typeof AdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/admin/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots/$sourceKey/$lotNumber': {
      id: '/lots/$sourceKey/$lotNumber'
      path: '/lots/$sourceKey/$lotNumber'
      fullPath: '/lots/$sourceKey/$lotNumber'
      preLoaderRoute: typeof LotsSourceKeyLotNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots/$lotId/reject': {
      id: '/lots/$lotId/reject'
      path: '/lots/$lotId/reject'
      fullPath: '/lots/$lotId/reject'
      preLoaderRoute: typeof LotsLotIdRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/runtime/$': {
      id: '/collector/runtime/$'
      path: '/$'
      fullPath: '/collector/runtime/$'
      preLoaderRoute: typeof CollectorRuntimeSplatRouteImport
      parentRoute: typeof CollectorRuntimeRoute
    }
    '/api/sold-price/results': {
      id: '/api/sold-price/results'
      path: '/api/sold-price/results'
      fullPath: '/api/sold-price/results'
      preLoaderRoute: typeof ApiSoldPriceResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sold-price/queue': {
      id: '/api/sold-price/queue'
      path: '/api/sold-price/queue'
      fullPath: '/api/sold-price/queue'
      preLoaderRoute: typeof ApiSoldPriceQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/vapid-key': {
      id: '/api/push/vapid-key'
      path: '/api/push/vapid-key'
      fullPath: '/api/push/vapid-key'
      preLoaderRoute: typeof ApiPushVapidKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/target-updates': {
      id: '/api/ingest/target-updates'
      path: '/target-updates'
      fullPath: '/api/ingest/target-updates'
      preLoaderRoute: typeof ApiIngestTargetUpdatesRouteImport
      parentRoute: typeof ApiIngestRoute
    }
    '/api/ingest/image-state': {
      id: '/api/ingest/image-state'
      path: '/image-state'
      fullPath: '/api/ingest/image-state'
      preLoaderRoute: typeof ApiIngestImageStateRouteImport
      parentRoute: typeof ApiIngestRoute
    }
    '/api/ingest/image': {
      id: '/api/ingest/image'
      path: '/image'
      fullPath: '/api/ingest/image'
      preLoaderRoute: typeof ApiIngestImageRouteImport
      parentRoute: typeof ApiIngestRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/targets/$targetId': {
      id: '/admin/targets/$targetId'
      path: '/$targetId'
      fullPath: '/admin/targets/$targetId'
      preLoaderRoute: typeof AdminTargetsTargetIdRouteImport
      parentRoute: typeof AdminTargetsRoute
    }
    '/admin/history/delete': {
      id: '/admin/history/delete'
      path: '/delete'
      fullPath: '/admin/history/delete'
      preLoaderRoute: typeof AdminHistoryDeleteRouteImport
      parentRoute: typeof AdminHistoryRoute
    }
    '/admin/targets/$targetId/remove': {
      id: '/admin/targets/$targetId/remove'
      path: '/remove'
      fullPath: '/admin/targets/$targetId/remove'
      preLoaderRoute: typeof AdminTargetsTargetIdRemoveRouteImport
      parentRoute: typeof AdminTargetsTargetIdRoute
    }
    '/admin/lots/$lotId/restore': {
      id: '/admin/lots/$lotId/restore'
      path: '/admin/lots/$lotId/restore'
      fullPath: '/admin/lots/$lotId/restore'
      preLoaderRoute: typeof AdminLotsLotIdRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lots/$lotId/remove': {
      id: '/admin/lots/$lotId/remove'
      path: '/admin/lots/$lotId/remove'
      fullPath: '/admin/lots/$lotId/remove'
      preLoaderRoute: typeof AdminLotsLotIdRemoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lots/$lotId/delete': {
      id: '/admin/lots/$lotId/delete'
      path: '/admin/lots/$lotId/delete'
      fullPath: '/admin/lots/$lotId/delete'
      preLoaderRoute: typeof AdminLotsLotIdDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lots/$lotId/approve': {
      id: '/admin/lots/$lotId/approve'
      path: '/admin/lots/$lotId/approve'
      fullPath: '/admin/lots/$lotId/approve'
      preLoaderRoute: typeof AdminLotsLotIdApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminHistoryRouteChildren {
  AdminHistoryDeleteRoute: typeof AdminHistoryDeleteRoute
}

const AdminHistoryRouteChildren: AdminHistoryRouteChildren = {
  AdminHistoryDeleteRoute: AdminHistoryDeleteRoute,
}

const AdminHistoryRouteWithChildren = AdminHistoryRoute._addFileChildren(
  AdminHistoryRouteChildren,
)

interface AdminTargetsTargetIdRouteChildren {
  AdminTargetsTargetIdRemoveRoute: typeof AdminTargetsTargetIdRemoveRoute
}

const AdminTargetsTargetIdRouteChildren: AdminTargetsTargetIdRouteChildren = {
  AdminTargetsTargetIdRemoveRoute: AdminTargetsTargetIdRemoveRoute,
}

const AdminTargetsTargetIdRouteWithChildren =
  AdminTargetsTargetIdRoute._addFileChildren(AdminTargetsTargetIdRouteChildren)

interface AdminTargetsRouteChildren {
  AdminTargetsTargetIdRoute: typeof AdminTargetsTargetIdRouteWithChildren
}

const AdminTargetsRouteChildren: AdminTargetsRouteChildren = {
  AdminTargetsTargetIdRoute: AdminTargetsTargetIdRouteWithChildren,
}

const AdminTargetsRouteWithChildren = AdminTargetsRoute._addFileChildren(
  AdminTargetsRouteChildren,
)

interface ApiIngestRouteChildren {
  ApiIngestImageRoute: typeof ApiIngestImageRoute
  ApiIngestImageStateRoute: typeof ApiIngestImageStateRoute
  ApiIngestTargetUpdatesRoute: typeof ApiIngestTargetUpdatesRoute
}

const ApiIngestRouteChildren: ApiIngestRouteChildren = {
  ApiIngestImageRoute: ApiIngestImageRoute,
  ApiIngestImageStateRoute: ApiIngestImageStateRoute,
  ApiIngestTargetUpdatesRoute: ApiIngestTargetUpdatesRoute,
}

const ApiIngestRouteWithChildren = ApiIngestRoute._addFileChildren(
  ApiIngestRouteChildren,
)

interface CollectorRuntimeRouteChildren {
  CollectorRuntimeSplatRoute: typeof CollectorRuntimeSplatRoute
}

const CollectorRuntimeRouteChildren: CollectorRuntimeRouteChildren = {
  CollectorRuntimeSplatRoute: CollectorRuntimeSplatRoute,
}

const CollectorRuntimeRouteWithChildren =
  CollectorRuntimeRoute._addFileChildren(CollectorRuntimeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  HealthRoute: HealthRoute,
  SoldRoute: SoldRoute,
  AdminHistoryRoute: AdminHistoryRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogoutRoute: AdminLogoutRoute,
  AdminSignupRoute: AdminSignupRoute,
  AdminTargetsRoute: AdminTargetsRouteWithChildren,
  ApiIngestRoute: ApiIngestRouteWithChildren,
  ApiLotsRoute: ApiLotsRoute,
  ApiScrapeConfigRoute: ApiScrapeConfigRoute,
  ApiSyncRunsRoute: ApiSyncRunsRoute,
  CollectorRuntimeRoute: CollectorRuntimeRouteWithChildren,
  ImagesImageIdRoute: ImagesImageIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiPushVapidKeyRoute: ApiPushVapidKeyRoute,
  ApiSoldPriceQueueRoute: ApiSoldPriceQueueRoute,
  ApiSoldPriceResultsRoute: ApiSoldPriceResultsRoute,
  LotsLotIdRejectRoute: LotsLotIdRejectRoute,
  LotsSourceKeyLotNumberRoute: LotsSourceKeyLotNumberRoute,
  AdminLotsLotIdApproveRoute: AdminLotsLotIdApproveRoute,
  AdminLotsLotIdDeleteRoute: AdminLotsLotIdDeleteRoute,
  AdminLotsLotIdRemoveRoute: AdminLotsLotIdRemoveRoute,
  AdminLotsLotIdRestoreRoute: AdminLotsLotIdRestoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
